// Auto-generated STOCHASTIC_AUDIO manifest
window.STOCHASTIC_TRACKLIST = [
  "MI+OM+RM/Ocean Man's Day At The Beach/01 cathedral brainpiece.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/02 auralbinaryneuroflora.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/03 one place i protect.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/04 misterinterview.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/05 the landscape of science without magic.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/06 the view from a distance with prediction.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/07 meline.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/08 the lost track....m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/09 sadmein.m4a",
  "MI+OM+RM/Ocean Man's Day At The Beach/10 blotte.m4a",
  "MI+OM+RM/Silver EP/01 nick and jesse by the statue.m4a",
  "MI+OM+RM/Silver EP/02 air ship dream.m4a",
  "MI+OM+RM/Silver EP/03 converse of self.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/01 need a ride_.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/02 cashless crimescene dodgescene.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/03 kate's favorite.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/04 pit stop for a generation.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/05 in the pickle jar.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/06 nowarpls.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/07 meline.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/08 air ship dream.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/09 a bowling argument replay.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/10 aeom.m4a",
  "MI+OM+RM/cashless crime scene dodge scene/12 uh, no.m4a",
  "MI+OM+RM/d'albsen kumor'a/01 01 XSYL.m4a",
  "MI+OM+RM/d'albsen kumor'a/02 02 ENWO (suffocation eruption).m4a",
  "MI+OM+RM/d'albsen kumor'a/03 03 SFJR.m4a",
  "MI+OM+RM/d'albsen kumor'a/04 04 OHGW.m4a",
  "MI+OM+RM/d'albsen kumor'a/05 05 XJWZ.m4a",
  "MI+OM+RM/d'albsen kumor'a/06 06 HLSF.m4a",
  "MI+OM+RM/d'albsen kumor'a/07 07 DGDA.m4a",
  "MI+OM+RM/d'albsen kumor'a/08 08 ABKE.m4a",
  "MI+OM+RM/d'albsen kumor'a/09 09 QDKU.m4a",
  "MI+OM+RM/d'albsen kumor'a/10 10 SHXI (the receding solid forces).m4a",
  "MI+OM+RM/d'albsen kumor'a/11 11 CQNW.m4a",
  "MI+OM+RM/maxell green/01 monomania.m4a",
  "MI+OM+RM/maxell green/02 reverse drowning.m4a",
  "MI+OM+RM/maxell green/03 Gehenna.m4a",
  "MI+OM+RM/maxell green/04 take of your panth.m4a",
  "MI+OM+RM/maxell green/05 sky, hair, sand (uncomfortable).m4a",
  "MI+OM+RM/maxell green/06 fear of crying.m4a",
  "MI+OM+RM/maxell green/07 sinus state.m4a",
  "MI+OM+RM/maxell green/08 love for a scraggley carrot.m4a",
  "MI+OM+RM/maxell orange/01 voidrunner's theme.m4a",
  "MI+OM+RM/maxell orange/02 cathedral brainpiece.m4a",
  "MI+OM+RM/maxell orange/03 running lynx.m4a",
  "MI+OM+RM/maxell orange/04 my favorite blue.m4a",
  "MI+OM+RM/maxell orange/05 kate's favorite.m4a",
  "MI+OM+RM/maxell orange/06 cuphuice.m4a",
  "MI+OM+RM/maxell orange/07 monret.m4a",
  "MI+OM+RM/maxell orange/08 meline.m4a",
  "MI+OM+RM/maxell orange/09 a new dress.m4a",
  "MI+OM+RM/maxell orange/10 untitled.m4a",
  "MI+OM+RM/maxell orange/11 the receding solid forces.m4a",
  "MI+OM+RM/maxell orange/12 rain forest run.m4a",
  "MI+OM+RM/maxell orange/13 misterinterview.m4a",
  "MI+OM+RM/maxell orange/14 one place i protect.m4a",
  "MI+OM+RM/maxell orange/15 unskinterrupted.m4a",
  "MI+OM+RM/maxell orange/16 need a ride_.m4a",
  "MI+OM+RM/skinterrupt's mix/01 eugh.m4a",
  "MI+OM+RM/skinterrupt's mix/02 voidrunner's theme.m4a",
  "MI+OM+RM/skinterrupt's mix/03 cathedral brainpiece.m4a",
  "MI+OM+RM/skinterrupt's mix/04 my favorite blue.m4a",
  "MI+OM+RM/skinterrupt's mix/05 mike's favorite red.m4a",
  "MI+OM+RM/skinterrupt's mix/06 monret.m4a",
  "MI+OM+RM/skinterrupt's mix/07 kate's favorite.m4a",
  "MI+OM+RM/skinterrupt's mix/08 a new dress.m4a",
  "MI+OM+RM/skinterrupt's mix/09 unskinterrupted.m4a",
  "MI+OM+RM/skinterrupt's mix/10 the receding solid forces.m4a",
  "MI+OM+RM/skinterrupt's mix/11 one place i protect.m4a",
  "MI+OM+RM/skinterrupt's mix/12 misterinterview.m4a",
  "MI+OM+RM/skinterrupt's mix/13 rain forest run.m4a",
  "MI+OM+RM/the bay/11 the bay.m4a"
];
