const fs = require('fs');
const path = require('path');

const VISUALS_DIR = 'visuals';
const MUSIC_DIR = 'MI+OM+RM';
const MANIFEST_PATH = 'js/media-manifest.js';

function getFiles(dir, filter) {
    let results = [];
    if (!fs.existsSync(dir)) return results;
    
    const list = fs.readdirSync(dir);
    list.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat && stat.isDirectory()) {
            results = results.concat(getFiles(filePath, filter));
        } else if (filter.test(file)) {
            results.push(filePath);
        }
    });
    return results;
}

// Focus purely on images for now (as requested)
const imageFilter = /\.(jpg|jpeg|png|gif|webp)$/i;

console.log('--- SME Media Indexer ---');
const visuals = getFiles(VISUALS_DIR, imageFilter);
console.log(`Found ${visuals.length} images in ${VISUALS_DIR}`);

const albumArt = getFiles(MUSIC_DIR, imageFilter);
console.log(`Found ${albumArt.length} images in ${MUSIC_DIR}`);

const allMedia = [...visuals, ...albumArt];

const manifestContent = `/**
 * media-manifest.js - Auto-generated by tools/index-media.js
 * Stochastic Media Engine (SME) source manifest.
 */
window.STOCHASTIC_MEDIA_MANIFEST = ${JSON.stringify(allMedia, null, 2)};
`;

fs.writeFileSync(MANIFEST_PATH, manifestContent);
console.log(`Manifest generated: ${MANIFEST_PATH} (${allMedia.length} assets total)`);
console.log('-------------------------');
